# Generated by Django 6.0.5 on 2026-06-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('hex', models.CharField(help_text='Например: #FF5733', max_length=7, verbose_name='HEX-код')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (сом)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('size', models.CharField(blank=True, help_text='Например: 10×8×5 см', max_length=100, verbose_name='Размер')),
                ('weight', models.CharField(blank=True, help_text='Например: 120 г', max_length=50, verbose_name='Вес')),
                ('print_time', models.CharField(blank=True, help_text='Например: 4 часа', max_length=50, verbose_name='Время печати')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.collection', verbose_name='Коллекция')),
                ('colors', models.ManyToManyField(blank=True, to='catalog.color', verbose_name='Доступные цвета')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
